### ISSUE TITLE
phpwhois error running php version 7.1.14

### ISSUE THREAD

**Issue by adamchilcott** [charlesabarnes/SPFtoolbox#21]
Appears to be an issue with phpwhois

```
https://mycooldomain.lan/SPFtoolbox/getWhois.php?domain=abc.net.au

<br />
<b>Warning</b>:  Illegal string offset 'domain' in <b>/Volumes/MyMagicDrive/SuperSecret/Directory/Apache/SPFtoolbox/phpwhois/whois.parser.php(370) : eval()'d code</b> on line <b>1</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Cannot use string offset as an array in /Volumes/MyMagicDrive/SuperSecret/Directory/Apache/SPFtoolbox/phpwhois/whois.parser.php(370) : eval()'d code:1
Stack trace:
#0 /Volumes/MyMagicDrive/SuperSecret/Directory/Apache/SPFtoolbox/phpwhois/whois.parser.php(370): eval()
#1 /Volumes/MyMagicDrive/SuperSecret/Directory/Apache/SPFtoolbox/phpwhois/whois.au.php(54): generic_parser_b(Array, Array)
#2 /Volumes/MyMagicDrive/SuperSecret/Directory/Apache/SPFtoolbox/phpwhois/whois.client.php(472): au_handler-&gt;parse(Array, 'abc.net.au')
#3 /Volumes/MyMagicDrive/SuperSecret/Directory/Apache/SPFtoolbox/phpwhois/whois.client.php(257): WhoisClient-&gt;Process(Array, true)
#4 /Volumes/MyMagicDrive/SuperSecret/Directory/Apache/SPFtoolbox/phpwhois/whois.main.php(259): WhoisClient-&gt;GetData('abc.net.au', true)
#5 /Volumes/MyMagicDrive/SuperSecret/Directory/Apache/SPFtoolbox/getWhois.php(15): Whois-&gt;Lookup('abc.net.au')
#6 {main}
  thrown in <b>/Volumes/MyMagicDrive/SuperSecret/Directory/Apache/SPFtoolbox/phpwhois/whois.parser.php(370) : eval()'d code</b> on line <b>1</b><br />
```
Client Side:
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Comment by roxyschram** [comment]
Receiving error 500 when searching '.com' domains. PHP version 7.1.14 as well. IIS 10, Windows server 2016.

Searching other '.co.uk' domains works as expected.

**Comment by roxyschram** [comment]
Resolved issue by installing 7.0.x along side of 7.1.14. With IIS 10, it automatically switch the "site" to an earlier version and now all works great.

**Comment by charlesabarnes** [comment]
I am working to programmatically fix this error but whenever I debug it it works.

**Comment by roxyschram** [comment]
If there is anything I can do to assist, feel free to ask.

**Comment by mjhdcode** [comment]
I'm having this same error - php 7.2, CentOS 7, Apache:
PHP Fatal error: Uncaught Error: Cannot use string offset as an array in var/www/html/whois/phpwhois/whois.parser.php(370) : eval()'d code:1 
Stack trace:
#0

**Comment by mjhdcode** [comment]
roxyschram solution works -> just install PHP70 and run fpm on a different port

**Comment by charlesabarnes** [comment]
this should be fixed. Let me know if you see any more problems
